# roles/glpi_ldap/tasks/main.yml
---
- name: Installer les paquets LDAP
  apt:
    name:
      - php-ldap
      - ldap-utils
      - openssl
    state: present
    update_cache: true

- name: Copier le certificat CA AD
  copy:
    src: "{{ ldap_ca_cert_src }}"
    dest: /tmp/ad-ca.cer

- name: Convertir le certificat en .crt
  command:
    cmd: >
      openssl x509 -inform DER
      -in /tmp/ad-ca.cer
      -out {{ ldap_ca_cert_remote_path }}

- name: Déclarer la CA LDAP
  lineinfile:
    path: /etc/ldap/ldap.conf
    line: "TLS_CACERT {{ ldap_ca_cert_remote_path }}"
    create: true

- name: Mettre à jour les certificats
  command: update-ca-certificates

- name: Tester LDAPS
  command:
    argv:
      - ldapwhoami
      - -x
      - -H
      - "{{ ldap_uri }}"
      - -D
      - "{{ ldap_bind_dn }}"
      - -w
      - "{{ vault_service_account_password }}"
  no_log: false

- name: Chiffrer le mot de passe LDAP avec GLPI
  ansible.builtin.command: >
    php -r 'chdir("{{ glpi_install_dir }}");
    require_once "vendor/autoload.php";
    if (!defined("GLPI_CONFIG_DIR")) { define("GLPI_CONFIG_DIR", "{{ glpi_install_dir }}/config"); }
    echo (new GLPIKey())->encrypt("{{ vault_service_account_password }}");'
  register: glpi_ldap_encrypted_password
  changed_when: false
  no_log: false

- name: Supprimer l'ancienne configuration LDAPS GLPI
  community.mysql.mysql_query:
    login_unix_socket: /run/mysqld/mysqld.sock
    login_db: "{{ glpi_db_name }}"
    query: >
      DELETE FROM glpi_authldaps
      WHERE name = '{{ ldap_name }}';
  no_log: true

- name: Créer la configuration LDAPS GLPI avec mot de passe chiffré
  community.mysql.mysql_query:
    login_unix_socket: /run/mysqld/mysqld.sock
    login_db: "{{ glpi_db_name }}"
    query: |
      INSERT INTO glpi_authldaps
      (
        name, host, port, basedn, rootdn, rootdn_passwd,
        `condition`, login_field, sync_field,
        use_tls, use_bind, is_active, is_default,
        date_creation, date_mod
      )
      VALUES
      (
        '{{ ldap_name }}',
        '{{ ldap_uri }}',
        {{ ldap_port }},
        '{{ ldap_base_dn }}',
        '{{ ldap_bind_dn }}',
        '{{ glpi_ldap_encrypted_password.stdout }}',
        '{{ ldap_user_filter }}',
        '{{ ldap_login_field }}',
        '{{ ldap_sync_field }}',
        0,
        1,
        1,
        1,
        NOW(),
        NOW()
      );
  no_log: true

- name: Synchroniser les utilisateurs LDAP dans GLPI
  ansible.builtin.command:
    argv:
      - sudo
      - -u
      - www-data
      - php
      - bin/console
      - glpi:ldap:synchronize_users
      - --only-create-new
      - --no-interaction
  args:
    chdir: "{{ glpi_install_dir }}"
  changed_when: false