server_hostname: srv-glpi
server_fqdn: glpi.cynto.tech

netplan_interface: "{{ ansible_default_ipv4.interface }}"
server_ip_cidr: 192.168.1.51/24
server_gateway: 192.168.1.254
server_dns:
  - 192.168.1.60
  - 192.168.1.61

timezone: Europe/Paris