# inventories/prod/hosts.yml
---
all:
  children:
    glpi:
      hosts:
        srv-glpi:
          ansible_host: 192.168.1.51
          ansible_user: nicolas
          ansible_password: "{{ vault_ansible_ssh_password }}"
          ansible_become_password: "{{ vault_ansible_become_password }}"